
# install packages to allow apt to use a repository over HTTPS:
- name: Install docker packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

# # curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
# - name: Add Docker s official GPG key[debian]
#   apt_key:
#     url: https://download.docker.com/linux/debian/gpg
#     state: present

# curl -fsSL https://download.docker.com/linux/raspbian/gpg | sudo apt-key add -
- name: Add Docker s official GPG key[raspbian]
  apt_key:
    url: https://download.docker.com/linux/raspbian/gpg
    state: present



# apt-key fingerprint
- name: Verify that we have the key with the fingerprint
  apt_key:
    id: 0EBFCD88
    state: present

# add-apt-repository
- name: Set up the stable repository for raspbian
  apt_repository:
    repo: deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/raspbian  "bullseye" stable
    state: present
    update_cache: yes

# # add-apt-repository
# - name: Set up the stable repository for Debian
#   apt_repository:
#     repo: deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/raspbian  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable
#     state: present
#     update_cache: yes


# install docker-ce latetst verion
- name: Install docker
  apt:
    name: "{{docker_installation_packages}}"
    state: present
    update_cache: yes
    
# sudo groupadd docker
- name: Create "docker" group
  group:
    name: "docker"
    state: present

# sudo usermod -aG docker r2-user
- name: Add remote "ubuntu" user to "docker" group
  user:
    name: "r2-user"
    group: "docker"
    append: yes

- name: Ensure docker deamon is running
  service:
    name: docker
    state: started
  tags: services, pi
  become: true

- name: Ensure My docker container is running
  docker_container:
    name: hello-world
    image: hello-world
    state: started
  tags: services, pi
  become: true

- name: "Install Common packages"
  apt:
    name: ['docker-compose']
    state: latest
  tags: installation, packages, pi


# - name: "Python Docker"
#   pip:
#     name: 
#       - docker
#   tags: python

# - name: "Install Minikube"
#   shell: 
#     cmd: curl -Lo ~/k3s https://storage.googleapis.com/minikube/releases/latest/minikube-linux-arm && chmod +x ~/minikube && mkdir -p /usr/local/bin/ && install ~/minikube /usr/local/bin/
#   tags: installation, k3s